export const FRAMEWORKS = [
  "Porter's Five Forces",
  'SWOT',
  'PESTLE',
  'BCG Matrix',
  'Ansoff Matrix',
  'Value Chain Analysis',
  'STP',
  '4Ps/7Ps',
  'Jobs To Be Done',
  'Brand Pyramid',
  'Customer Journey Mapping',
  'Business Model Canvas',
  'Lean Canvas',
  'Unit Economics',
  'Flywheel vs Funnel',
  'First Principles',
  'Second Order Thinking',
  'Inversion',
  'Pre-mortem',
  'Eisenhower Matrix',
]

export const ROW_DEFS = [
  { id: 'week-1',  label: 'Week 1',  sublabel: 'Headspace',                         weekNumber: 1,    expectsCaseStudy: false },
  { id: 'week-2',  label: 'Week 2',  sublabel: 'Numbers, Statistics & Excel',       weekNumber: 2,    expectsCaseStudy: false },
  { id: 'week-3',  label: 'Week 3',  sublabel: 'Marketing',                         weekNumber: 3,    expectsCaseStudy: true  },
  { id: 'week-4',  label: 'Week 4',  sublabel: 'Strategy',                          weekNumber: 4,    expectsCaseStudy: true  },
  { id: 'week-5',  label: 'Week 5',  sublabel: 'Entrepreneurship I',                weekNumber: 5,    expectsCaseStudy: true  },
  { id: 'week-6',  label: 'Week 6',  sublabel: 'Entrepreneurship II',               weekNumber: 6,    expectsCaseStudy: true  },
  { id: 'week-7',  label: 'Week 7',  sublabel: 'Finance',                           weekNumber: 7,    expectsCaseStudy: true  },
  { id: 'week-8',  label: 'Week 8',  sublabel: 'Operations',                        weekNumber: 8,    expectsCaseStudy: true  },
  { id: 'week-9',  label: 'Week 9',  sublabel: 'Leadership & Data',                 weekNumber: 9,    expectsCaseStudy: true  },
  { id: 'week-10', label: 'Week 10', sublabel: 'Purpose of the Firm',               weekNumber: 10,   expectsCaseStudy: true  },
  { id: 'week-11', label: 'Week 11', sublabel: 'Consumer Psychology & Behaviour',   weekNumber: 11,   expectsCaseStudy: true  },
  { id: 'week-12', label: 'Week 12', sublabel: 'Brand Dissections',                 weekNumber: 12,   expectsCaseStudy: true  },
  { id: 'week-13', label: 'Week 13', sublabel: 'India Lens',                        weekNumber: 13,   expectsCaseStudy: false },
  { id: 'anytime', label: 'Anytime', sublabel: 'Performance & People',              weekNumber: null, expectsCaseStudy: false },
]
